version: '3'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=https://d32sl91owll8mu.cloudfront.net


  server:
    build: ./server
    ports:
      - "8080:8080"
