version: '3'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080


  server:
    build: ./server
    ports:
      - "8080:8080"
